import { useState } from 'react';
import { Archive, Landmark, Plus, Wallet, WalletCards } from 'lucide-react';
import { endpoints } from '../api/client.js';
import { useApp } from '../context/useApp.js';
import { useData } from '../hooks/useData.js';
import { formatMoney } from '../utils/format.js';
import { EmptyState, Modal, PageHeader, Spinner, StatusBadge } from '../components/ui.jsx';

const colors = ['#1f6f54', '#2563eb', '#7c3aed', '#dc6b5d', '#c18b2b'];
function AccountForm({ open, onClose, onSaved }) { const { toast, settings } = useApp(); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ name: '', type: 'bank', currency: settings.defaultCurrency || 'DZD', openingBalance: 0, color: colors[0] }); const set = (k) => (e) => setForm((v) => ({ ...v, [k]: e.target.value })); async function submit(e) { e.preventDefault(); setBusy(true); try { await endpoints.create('accounts', form); toast('Account created'); onSaved(); onClose(); } catch (err) { toast(err.message, 'error'); } finally { setBusy(false); } } return <Modal open={open} onClose={onClose} title="Add account" description="Opening balance becomes the starting point for this ledger"><form onSubmit={submit} className="space-y-4"><label><span className="label">Account name</span><input required autoFocus className="field" value={form.name} onChange={set('name')} placeholder="e.g. Main bank"/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Type</span><select className="field" value={form.type} onChange={set('type')}><option>cash</option><option>bank</option><option>savings</option><option>wallet</option><option>other</option></select></label><label><span className="label">Currency</span><input required maxLength="3" className="field uppercase" value={form.currency} onChange={set('currency')}/></label></div><label><span className="label">Opening balance</span><input type="number" step="0.01" className="field" value={form.openingBalance} onChange={set('openingBalance')}/></label><div><span className="label">Color</span><div className="flex gap-2">{colors.map((color) => <button type="button" key={color} onClick={() => setForm((v) => ({ ...v, color }))} className={`h-9 w-9 rounded-full ${form.color === color ? 'ring-2 ring-ink ring-offset-2 dark:ring-lime dark:ring-offset-[#151c18]' : ''}`} style={{ background: color }} />)}</div></div><button disabled={busy} className="btn-primary w-full">{busy ? 'Creating…' : 'Create account'}</button></form></Modal>; }

export default function Accounts() { const { toast, settings } = useApp(); const [open, setOpen] = useState(false); const { data, loading, error, reload } = useData(() => endpoints.list('accounts'), []); const accounts = data?.data || []; const total = accounts.reduce((sum, a) => sum + a.currentBalance, 0); async function archive(account) { if (!window.confirm(`Archive ${account.name}? Its history will stay intact.`)) return; try { await endpoints.create(`accounts/${account._id}/archive`, {}); toast('Account archived'); reload(); } catch (err) { toast(err.message, 'error'); } } return <><PageHeader eyebrow="Money" title="Accounts" description="Your wallets and balances, reconstructed from the source ledger." actions={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={17}/>Add account</button>}/><div className="mb-5 flex items-end justify-between rounded-2xl bg-ink p-6 text-white shadow-soft dark:bg-[#1b2721]"><div><p className="text-xs font-semibold text-white/55">Total across active accounts</p><p className="mt-2 font-display text-3xl font-bold">{formatMoney(total, settings.defaultCurrency)}</p></div><WalletCards className="text-lime" size={34}/></div>{loading ? <Spinner/> : error ? <EmptyState icon={Wallet} title="Accounts unavailable" description={error}/> : accounts.length === 0 ? <EmptyState icon={Wallet} title="Create your first account" description="Add cash, a bank account or a savings wallet." action={<button className="btn-primary" onClick={() => setOpen(true)}>Add account</button>}/> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{accounts.map((account) => <article key={account._id} className="panel group overflow-hidden"><div className="h-1.5" style={{ background: account.color }}/><div className="p-5"><div className="mb-8 flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl text-white" style={{ background: account.color }}>{account.type === 'bank' ? <Landmark size={20}/> : <Wallet size={20}/>}</span><button className="icon-btn opacity-50 group-hover:opacity-100" onClick={() => archive(account)} aria-label="Archive account"><Archive size={16}/></button></div><p className="text-sm font-semibold text-[#6e7a72] dark:text-[#9eaaa2]">{account.name}</p><p className="mt-1 font-display text-2xl font-bold">{formatMoney(account.currentBalance, account.currency)}</p><div className="mt-5 flex items-center justify-between"><StatusBadge>{account.type}</StatusBadge><p className="text-[10px] text-[#8c958f]">Opening {formatMoney(account.openingBalance, account.currency)}</p></div></div></article>)}</section>}<AccountForm open={open} onClose={() => setOpen(false)} onSaved={reload}/></>; }
