import { useState } from 'react';
import { BookOpenText, Check, ContactRound, FolderKanban, HeartPulse, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { endpoints } from '../api/client.js';
import { useApp } from '../context/useApp.js';
import { useData } from '../hooks/useData.js';
import { formatDate, formatMoney } from '../utils/format.js';
import { EmptyState, Modal, PageHeader, Spinner, StatusBadge } from '../components/ui.jsx';

const configs = {
  contacts: { title: 'Contacts', eyebrow: 'People', description: 'The people connected to your plans and finances.', icon: ContactRound, fields: [['name', 'Name', 'text'], ['phone', 'Phone', 'tel'], ['email', 'Email', 'email'], ['telegram', 'Telegram', 'text'], ['notes', 'Notes', 'textarea']] },
  projects: { title: 'Projects', eyebrow: 'Planning', description: 'A home for outcomes that need more than one task.', icon: FolderKanban, fields: [['name', 'Project name', 'text'], ['description', 'Description', 'textarea'], ['status', 'Status', 'select:planned,active,on_hold,completed,cancelled'], ['targetDate', 'Target date', 'date']] },
  notes: { title: 'Notes', eyebrow: 'Personal', description: 'Ideas, reference and context worth keeping close.', icon: BookOpenText, fields: [['title', 'Title', 'text'], ['content', 'Note', 'textarea']] },
  habits: { title: 'Habits', eyebrow: 'Rhythm', description: 'Small actions, made visible enough to repeat.', icon: HeartPulse, fields: [['name', 'Habit name', 'text'], ['frequency', 'Frequency', 'select:daily,weekdays,weekly'], ['target', 'Target', 'number']] },
  wishlist: { title: 'Wishlist', eyebrow: 'Someday', description: 'Keep purchases intentional and connected to your goals.', icon: ShoppingBag, fields: [['name', 'Item', 'text'], ['expectedPrice', 'Expected price', 'number'], ['priority', 'Priority', 'select:low,medium,high'], ['status', 'Status', 'select:wanted,saving,purchased,cancelled'], ['url', 'Link', 'url'], ['notes', 'Notes', 'textarea']] },
};

function ResourceForm({ kind, open, onClose, onSaved }) { const { toast } = useApp(); const config = configs[kind]; const initial = Object.fromEntries(config.fields.map(([key, , type]) => [key, type.startsWith('select:') ? type.split(':')[1].split(',')[0] : type === 'number' ? 1 : ''])); const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const set = (k) => (e) => setForm((v) => ({ ...v, [k]: e.target.value })); async function submit(e) { e.preventDefault(); setBusy(true); try { await endpoints.create(kind, form); toast(`${config.title.slice(0, -1)} added`); onSaved(); onClose(); } catch (err) { toast(err.message, 'error'); } finally { setBusy(false); } } return <Modal open={open} onClose={onClose} title={`Add ${config.title.slice(0, -1).toLowerCase()}`}><form className="space-y-4" onSubmit={submit}>{config.fields.map(([key, label, type], index) => <label key={key}><span className="label">{label}</span>{type === 'textarea' ? <textarea autoFocus={index === 0} required={index === 0} rows="4" className="field h-auto py-3" value={form[key]} onChange={set(key)}/> : type.startsWith('select:') ? <select className="field capitalize" value={form[key]} onChange={set(key)}>{type.split(':')[1].split(',').map((v) => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select> : <input autoFocus={index === 0} required={index === 0} type={type} min={type === 'number' ? 0 : undefined} className="field" value={form[key]} onChange={set(key)}/>}</label>)}<button disabled={busy} className="btn-primary w-full">{busy ? 'Saving…' : 'Save'}</button></form></Modal>; }

function Card({ kind, item, onRemove, onLog, currency }) { if (kind === 'contacts') return <article className="panel p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#edf2ed]"><ContactRound size={18}/></span><button className="icon-btn" onClick={onRemove}><Trash2 size={15}/></button></div><h3 className="mt-4 font-display font-bold">{item.name}</h3><p className="mt-1 text-xs text-[#7c8780]">{item.phone || item.email || item.telegram || 'No contact details'}</p><p className="mt-3 line-clamp-2 text-xs text-[#8b948e]">{item.notes}</p></article>;
  if (kind === 'notes') return <article className="panel p-5"><div className="flex items-start justify-between"><h3 className="font-display font-bold">{item.title}</h3><button className="icon-btn" onClick={onRemove}><Trash2 size={15}/></button></div><p className="mt-3 whitespace-pre-line text-sm leading-6 text-[#657168] dark:text-[#adb8b0]">{item.content || 'Empty note'}</p><p className="mt-4 text-[10px] text-[#8a948d]">Updated {formatDate(item.updatedAt)}</p></article>;
  if (kind === 'habits') { const today = new Date().toISOString().slice(0, 10); const done = item.logs?.some((log) => log.date?.slice(0, 10) === today); return <article className="panel p-5"><div className="flex items-start justify-between"><div><StatusBadge tone={item.active ? 'success' : 'neutral'}>{item.frequency}</StatusBadge><h3 className="mt-3 font-display text-lg font-bold">{item.name}</h3></div><button onClick={onLog} disabled={done} className={`grid h-11 w-11 place-items-center rounded-xl ${done ? 'bg-emerald-100 text-emerald-700' : 'border border-[#d8ded8] hover:bg-[#f1f4ef] dark:border-white/10'}`}><Check size={20}/></button></div><p className="mt-6 text-xs text-[#7d8881]">{item.logs?.length || 0} total check-ins · target {item.target}</p></article>; }
  if (kind === 'wishlist') return <article className="panel p-5"><div className="flex justify-between"><StatusBadge tone={item.status === 'purchased' ? 'success' : item.priority === 'high' ? 'warning' : 'neutral'}>{item.status}</StatusBadge><button className="icon-btn" onClick={onRemove}><Trash2 size={15}/></button></div><h3 className="mt-4 font-display text-lg font-bold">{item.name}</h3><p className="mt-1 text-xl font-bold text-accent dark:text-lime">{formatMoney(item.expectedPrice, currency)}</p><p className="mt-3 text-xs capitalize text-[#7d8881]">{item.priority} priority</p></article>;
  return <article className="panel p-5"><div className="flex items-start justify-between"><StatusBadge tone={item.status === 'completed' ? 'success' : 'info'}>{item.status}</StatusBadge><button className="icon-btn" onClick={onRemove}><Trash2 size={15}/></button></div><h3 className="mt-4 font-display text-lg font-bold">{item.name}</h3><p className="mt-2 line-clamp-2 text-sm text-[#768179]">{item.description || 'No description yet.'}</p><p className="mt-5 text-xs text-[#89928c]">Target {formatDate(item.targetDate)}</p></article>; }

export default function Personal({ kind }) { const { toast, settings } = useApp(); const [open, setOpen] = useState(false); const config = configs[kind]; const { data, loading, error, reload } = useData(() => endpoints.list(kind), [kind]); const items = data?.data || []; async function remove(id) { if (!window.confirm('Delete this record?')) return; try { await endpoints.remove(kind, id); toast('Record deleted'); reload(); } catch (err) { toast(err.message, 'error'); } } async function log(id) { try { await endpoints.create(`habits/${id}/log`, { value: 1 }); toast('Habit checked in'); reload(); } catch (err) { toast(err.message, 'error'); } } return <><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} actions={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={17}/>Add</button>}/>{loading ? <Spinner/> : error ? <EmptyState icon={config.icon} title={`${config.title} unavailable`} description={error}/> : items.length === 0 ? <div className="panel"><EmptyState icon={config.icon} title={`No ${config.title.toLowerCase()} yet`} description="Add the first one when it is useful." action={<button className="btn-primary" onClick={() => setOpen(true)}>Add one</button>}/></div> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item._id} kind={kind} item={item} currency={settings.defaultCurrency} onRemove={() => remove(item._id)} onLog={() => log(item._id)}/>)}</section>}<ResourceForm key={kind} kind={kind} open={open} onClose={() => setOpen(false)} onSaved={reload}/></>; }
