import { z } from 'zod';

const clock = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const integer = (min, max) => z.coerce.number().int().min(min).max(max);
const section = (shape) => z.object(shape).strict();
export const automationSettingsInput = z.object({
  general: section({ enabled: z.boolean(), workerEnabled: z.boolean(), timezoneBehavior: z.enum(['user', 'utc']), activeStart: clock, activeEnd: clock, quietEnabled: z.boolean(), quietStart: clock, quietEnd: clock }),
  dailyFocus: section({ enabled: z.boolean(), maxTasks: integer(1, 10), morningEnabled: z.boolean(), morningTime: clock, planningReminderEnabled: z.boolean(), planningReminderIntervalMinutes: integer(15, 1440), maxPlanningReminders: integer(0, 10), taskReminderEnabled: z.boolean(), taskReminderTime: clock, taskReminderIntervalMinutes: integer(15, 1440), maxTaskReminders: integer(0, 10), eveningEnabled: z.boolean(), eveningTime: clock }),
  taskExecution: section({ nextActionPromptsEnabled: z.boolean(), nextActionMinimumDays: integer(0, 365), startFollowUpEnabled: z.boolean(), startCheckInDelayMinutes: integer(15, 10080), maxStartCheckIns: integer(0, 10) }),
  thresholds: section({ farDays: integer(1, 3650), mediumDays: integer(1, 3650), nearDays: integer(1, 3650), urgentDays: integer(0, 3650), highPriorityLeadDays: integer(0, 365), urgentPriorityLeadDays: integer(0, 365), farIntervalDays: integer(1, 365), mediumIntervalDays: integer(1, 365), nearIntervalDays: integer(1, 365), urgentIntervalHours: integer(1, 720), overdueIntervalHours: integer(1, 720) }),
  escalation: section({ maxNormalReminders: integer(0, 100), postponeThreshold: integer(1, 100), ignoreThreshold: integer(1, 100), forceDecisionThreshold: integer(1, 100), maxLevel: integer(0, 2), cooldownMinutes: integer(15, 10080) }),
  reminderBehavior: section({ allowBundling: z.boolean(), bundleLowPriority: z.boolean(), duplicateSuppressionMinutes: integer(0, 10080), dailyFocusPriorityBoost: z.boolean(), requireAcknowledgementFrom: z.enum(['none', 'low', 'medium', 'high', 'urgent']), blockedTaskPolicy: z.enum(['pause', 'review']) }),
}).strict().refine((v) => v.thresholds.farDays > v.thresholds.mediumDays && v.thresholds.mediumDays > v.thresholds.nearDays && v.thresholds.nearDays > v.thresholds.urgentDays, { message: 'Deadline thresholds must be ordered far > medium > near > urgent', path: ['thresholds'] }).refine((v) => v.escalation.forceDecisionThreshold >= v.escalation.postponeThreshold && v.escalation.forceDecisionThreshold >= v.escalation.ignoreThreshold, { message: 'Force decision threshold must be at least the postpone and ignore thresholds', path: ['escalation'] }).refine((v) => v.dailyFocus.morningTime < v.dailyFocus.eveningTime, { message: 'Morning planning must be before evening review', path: ['dailyFocus'] });
