import mongoose from 'mongoose';

const recurrenceSchema = new mongoose.Schema(
  {
    frequency: { type: String, enum: ['daily', 'weekly', 'monthly', 'yearly'] },
    interval: { type: Number, min: 1, max: 365, default: 1 },
    daysOfWeek: [{ type: Number, min: 0, max: 6 }],
    dayOfMonth: { type: Number, min: 1, max: 31 },
    startDate: Date,
    endDate: Date,
  },
  { _id: false },
);

const reminderSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 180 },
    message: { type: String, default: '', maxlength: 2000 },
    source: { type: String, enum: ['automatic', 'custom'], default: 'custom' },
    entityType: {
      type: String,
      enum: ['task', 'debt', 'bill', 'subscription', 'goal', 'custom'],
      default: 'custom',
    },
    entityId: { type: mongoose.Schema.Types.ObjectId, default: null },
    purpose: { type: String, enum: ['prepare', 'act', 'follow_up', 'review'], default: 'act' },
    trigger: {
      type: {
        type: String,
        enum: ['datetime', 'relative', 'recurring', 'entity_event'],
        default: 'datetime',
      },
      at: Date,
      timezone: String,
      anchor: String,
      offsetMinutes: Number,
      recurrence: recurrenceSchema,
    },
    priority: { type: String, enum: ['low', 'medium', 'high', 'urgent'], default: 'medium' },
    mode: { type: String, enum: ['automatic', 'custom'], default: 'custom' },
    status: {
      type: String,
      enum: [
        'scheduled',
        'active',
        'snoozed',
        'waiting',
        'completed',
        'cancelled',
        'expired',
        'suppressed',
      ],
      default: 'scheduled',
    },
    requireAcknowledgement: { type: Boolean, default: false },
    followUp: {
      enabled: { type: Boolean, default: false },
      delayMinutes: { type: Number, default: 1440, min: 30, max: 10080 },
      maxCount: { type: Number, default: 1, min: 0, max: 3 },
    },
    autoGenerated: { type: Boolean, default: false },
    policyKey: { type: String, default: null },
    customized: { type: Boolean, default: false },
    nextTriggerAt: { type: Date, required: true },
    lastTriggeredAt: Date,
    deliveredAt: Date,
    acknowledgedAt: Date,
    completedAt: Date,
    snoozedUntil: Date,
    triggerCount: { type: Number, default: 0 },
    snoozeCount: { type: Number, default: 0 },
    followUpCount: { type: Number, default: 0 },
    blockedReason: String,
    blockedNote: String,
    deliveryChannels: { type: [String], default: ['telegram'] },
    processingAt: Date,
    processingBy: String,
    claimUntil: Date,
    metadata: mongoose.Schema.Types.Mixed,
    archived: { type: Boolean, default: false },
  },
  { timestamps: true, optimisticConcurrency: true },
);

reminderSchema.index({ status: 1, archived: 1, nextTriggerAt: 1, claimUntil: 1 });
reminderSchema.index({ user: 1, entityType: 1, entityId: 1, status: 1 });
reminderSchema.index(
  { user: 1, policyKey: 1 },
  { unique: true, partialFilterExpression: { policyKey: { $type: 'string' } } },
);
export const Reminder = mongoose.model('Reminder', reminderSchema);
