import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../src/config/db.js';
import { User } from '../src/models/User.js';
import { Task } from '../src/models/Task.js';
import { Reminder } from '../src/models/Reminder.js';
import { Goal } from '../src/models/Planning.js';
import { Setting } from '../src/models/Setting.js';
import { TelegramConnection } from '../src/models/TelegramConnection.js';
import { TelegramSession } from '../src/models/TelegramSession.js';
import { AccessSubscription } from '../src/models/AccessSubscription.js';
import { handleTelegramUpdate } from '../src/telegram/handler.js';
import { parseTelegramMessage } from '../src/telegram/parser.js';

const bot = vi.hoisted(() => ({ sendMessage: vi.fn().mockResolvedValue({ message_id: 1 }), telegramRequest: vi.fn().mockResolvedValue({}) }));
vi.mock('../src/telegram/botClient.js', () => bot);

let mongo;
let user;
const message = (text) => ({ message: { from: { id: 123 }, chat: { id: 321, type: 'private' }, text } });
const callback = (data) => ({ callback_query: { id: `cb-${data}`, data, from: { id: 123 }, message: { chat: { id: 321, type: 'private' }, message_id: 1 } } });
const send = (text) => handleTelegramUpdate(message(text));
const click = async (data) => {
  const start = ['add:task', 'add:reminder', 'add:goal'].includes(data);
  const session = start ? null : await TelegramSession.findOne({ telegramUserId: '123', chatId: '321' });
  return handleTelegramUpdate(callback(session?.payload?.flowId ? `${data}:${session.payload.flowId}` : data));
};
const pending = () => TelegramSession.findOne({ telegramUserId: '123', chatId: '321' });

beforeAll(async () => { mongo = await MongoMemoryServer.create(); await connectDatabase(mongo.getUri()); await Promise.all([TelegramSession.init(), Reminder.init()]); });
afterAll(async () => { await disconnectDatabase(); await mongo.stop(); });
beforeEach(async () => {
  await Promise.all([User.deleteMany(), Task.deleteMany(), Reminder.deleteMany(), Goal.deleteMany(), Setting.deleteMany(), TelegramConnection.deleteMany(), TelegramSession.deleteMany(), AccessSubscription.deleteMany()]);
  bot.sendMessage.mockClear(); bot.telegramRequest.mockClear();
  user = await User.create({ fullName: 'Guided owner', email: 'guided@example.com', passwordHash: 'unused' });
  await Setting.create({ user: user._id, timezone: 'Africa/Lagos' });
  await TelegramConnection.create({ user: user._id, telegramUserId: '123', chatId: '321' });
  await AccessSubscription.create({ user: user._id, plan: new mongoose.Types.ObjectId(), activationLink: new mongoose.Types.ObjectId(), startedAt: new Date(), activatedAt: new Date(), expiresAt: new Date(Date.now() + 86400000), planSnapshot: { name: 'Day', durationValue: 1, durationUnit: 'DAY' } });
});

describe('guided add', () => {
  it.each(['add', '/add', 'ADD'])('opens the existing quick menu from %s', async (word) => {
    await send(word);
    expect(bot.sendMessage.mock.calls.at(-1)[2]).toContain('What would you like to add?');
    const buttons = bot.sendMessage.mock.calls.at(-1)[3].inline_keyboard.flat();
    expect(buttons.map((button) => button.callback_data)).toEqual(expect.arrayContaining(['add:task', 'add:reminder', 'add:goal', 'quick:expense', 'quick:income', 'quick:din', 'quick:dout', 'quick:sale']));
  });

  it('creates a task through the task service and clears the flow', async () => {
    await send('add'); await click('add:task'); await send('Prepare proposal'); await click('add:priority:high'); await click('add:taskdue:tomorrow');
    const task = await Task.findOne({ user: user._id, title: 'Prepare proposal' });
    expect(task.priority).toBe('high');
    expect(task.taskReminderState).toBe('enabled');
    expect(task.createdVia).toBe('telegram');
    expect(task.dueDate).toBeTruthy();
    expect(await pending()).toBeNull();
    expect(bot.telegramRequest.mock.calls.filter((call) => call[1] === 'editMessageText').at(-1)[2].text).toContain('Task added');
  });

  it('creates a reminder from a natural time and supports custom date and time validation', async () => {
    await send('/add'); await click('add:reminder'); await send('Renew the domain');
    await send('in 3 hours');
    expect(await Reminder.countDocuments({ user: user._id, title: 'Renew the domain', autoGenerated: false })).toBe(1);
    expect(await pending()).toBeNull();
    await send('add'); await click('add:reminder'); await send('Call Ahmed');
    await click('add:remindday:choose'); await click('add:remindday:other');
    await send('2026-02-30');
    expect((await pending()).action).toBe('ADD_REMINDER_OTHER_DATE');
    const future = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);
    await send(future);
    await click('add:remindtime:other');
    await send('25:99');
    expect((await pending()).action).toBe('ADD_REMINDER_OTHER_TIME');
    await send('16:30');
    expect(await Reminder.countDocuments({ user: user._id, title: 'Call Ahmed' })).toBe(1);
    expect(await pending()).toBeNull();
  });

  it('uses local timezone for reminder preset buttons and validates title length', async () => {
    await send('add'); await click('add:reminder');
    await send('x'.repeat(181));
    expect((await pending()).action).toBe('ADD_REMINDER_TITLE');
    await send('Morning review'); await click('add:remindwhen:morning');
    const reminder = await Reminder.findOne({ user: user._id, title: 'Morning review' });
    expect(reminder).toBeTruthy();
    expect(new Intl.DateTimeFormat('en-GB', { timeZone: 'Africa/Lagos', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(reminder.nextTriggerAt)).toBe('09:00');
    expect(await pending()).toBeNull();
  });

  it('creates a personal goal with an optional target date', async () => {
    await send('add'); await click('add:goal'); await send('Launch Orbit ads'); await click('add:goaldate:month');
    const goal = await Goal.findOne({ user: user._id });
    expect(goal.title).toBe('Launch Orbit ads');
    expect(goal.type).toBe('personal');
    expect(goal.targetDate).toBeTruthy();
    expect(await pending()).toBeNull();
  });

  it('cancels, expires, and lets another command interrupt a flow', async () => {
    await send('add'); await click('add:task'); await send('/cancel');
    expect(await pending()).toBeNull();
    await send('add'); await click('add:task'); await click('add:cancel');
    expect(await pending()).toBeNull();
    await send('add'); await click('add:task'); await send('/tasks');
    expect(await pending()).toBeNull();
    expect(bot.sendMessage.mock.calls.at(-1)[2]).toContain('TASKS');
    await send('add'); await click('add:goal'); await send('Expired goal');
    await TelegramSession.updateOne({ telegramUserId: '123', chatId: '321' }, { $set: { expiresAt: new Date(Date.now() - 1000) } });
    await click('add:goaldate:month');
    expect(await Goal.countDocuments({ user: user._id })).toBe(0);
  });

  it('rejects a button from an earlier flow and duplicate completion clicks', async () => {
    await send('add'); await click('add:task'); await send('First');
    const oldId = (await pending()).payload.flowId;
    await send('add'); await click('add:task'); await send('Second');
    await handleTelegramUpdate(callback(`add:priority:urgent:${oldId}`));
    expect((await pending()).action).toBe('ADD_TASK_PRIORITY');
    await click('add:priority:high');
    const currentId = (await pending()).payload.flowId;
    await handleTelegramUpdate(callback(`add:taskdue:none:${currentId}`));
    await handleTelegramUpdate(callback(`add:taskdue:none:${currentId}`));
    expect(await Task.countDocuments({ user: user._id, title: 'Second' })).toBe(1);
  });

  it('preserves legacy natural-language and recurring reminder input', async () => {
    expect(parseTelegramMessage('Remind me to renew the domain next Thursday', { timezone: 'Africa/Lagos' }).intent).toBe('CREATE_REMINDER');
    expect(parseTelegramMessage('Remind me tomorrow at 5 PM to call Ahmed', { timezone: 'Africa/Lagos' }).intent).toBe('CREATE_REMINDER');
    expect(parseTelegramMessage('Remind me in 2 hours to send the invoice', { timezone: 'Africa/Lagos' }).intent).toBe('CREATE_REMINDER');
    expect(parseTelegramMessage('Remind me every month to pay rent', { timezone: 'Africa/Lagos' }).data.trigger.recurrence.frequency).toBe('monthly');
    await send('Remind me to renew the domain next Thursday');
    expect(await Reminder.countDocuments({ user: user._id, title: 'renew the domain', autoGenerated: false })).toBe(1);
    await send('Remind me every month to pay rent');
    expect((await Reminder.findOne({ user: user._id, title: 'pay rent' })).trigger.type).toBe('recurring');
  });
});
