import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc.js';
import timezone from 'dayjs/plugin/timezone.js';
import { Reminder } from '../models/Reminder.js';
import { ReminderEvent } from '../models/ReminderEvent.js';
import { Task } from '../models/Task.js';
import { TaskExecutionEvent } from '../models/TaskExecutionEvent.js';

dayjs.extend(utc); dayjs.extend(timezone);
const rank = { low: 0, medium: 1, high: 2, urgent: 3 };

export async function scheduleFocusTaskCues(userId, focus, settings, rules, now = new Date()) {
  if (!focus.planningCompleted || !rules.dailyFocus.taskReminderEnabled || !rules.dailyFocus.maxTaskReminders) return;
  const clock = dayjs(now).tz(focus.timezone).format('HH:mm');
  if (clock < rules.dailyFocus.taskReminderTime || clock >= rules.dailyFocus.eveningTime) return;
  for (const item of focus.items) {
    const task = item.task;
    if (!task || task.archived || task.reminderMode !== 'automatic' || ['completed', 'cancelled'].includes(task.status)) continue;
    if (task.executionState === 'started' && rules.taskExecution.startFollowUpEnabled) continue;
    if (task.executionState === 'blocked' && rules.reminderBehavior.blockedTaskPolicy === 'pause') continue;
    const key = `focus:${focus.date}:task:${task._id}`;
    const existing = await Reminder.findOne({ user: userId, policyKey: key });
    if (existing?.customized || ['completed', 'cancelled', 'waiting', 'suppressed', 'snoozed'].includes(existing?.status)) continue;
    if (existing) {
      if (existing.status !== 'active' || existing.triggerCount >= rules.dailyFocus.maxTaskReminders || !existing.deliveredAt) continue;
      if (now.getTime() - existing.deliveredAt.getTime() < rules.dailyFocus.taskReminderIntervalMinutes * 60000) continue;
      const marker = existing.deliveredAt.toISOString();
      const claimed = await Reminder.updateOne({ _id: existing._id, user: userId, status: 'active', 'metadata.requeuedFor': { $ne: marker } }, { $set: { status: 'scheduled', nextTriggerAt: new Date(now.getTime() + 60000), 'metadata.requeuedFor': marker } });
      if (claimed.modifiedCount && !existing.acknowledgedAt) {
        await Task.updateOne({ _id: task._id, user: userId }, { $inc: { ignoreCount: 1 } });
        await ReminderEvent.create({ user: userId, reminderId: existing._id, eventType: 'ignored' });
        await TaskExecutionEvent.create({ user: userId, task: task._id, focus: focus._id, type: 'ignored', channel: 'system' });
      }
      continue;
    }
    const priority = rules.reminderBehavior.dailyFocusPriorityBoost && ['low', 'medium'].includes(task.priority) ? 'high' : task.priority;
    const at = new Date(now.getTime() + 60000);
    const data = { user: userId, title: task.title, message: `Today's focus: ${task.title}${task.nextAction ? `\nNext: ${task.nextAction}` : ''}. Start when ready.`,
      source: 'automatic', mode: 'automatic', autoGenerated: true, entityType: 'task', entityId: task._id,
      purpose: 'act', priority, requireAcknowledgement: rules.reminderBehavior.requireAcknowledgementFrom !== 'none' && rank[priority] >= rank[rules.reminderBehavior.requireAcknowledgementFrom],
      trigger: { type: 'datetime', at, timezone: focus.timezone }, nextTriggerAt: at, status: 'scheduled', policyKey: key,
      deliveryChannels: Object.entries(settings.reminders?.deliveryChannels || { telegram: true }).filter(([, enabled]) => enabled).map(([name]) => name),
      metadata: { automation: 'focus-task', date: focus.date, focusId: focus._id } };
    try { const reminder = await Reminder.create(data); await ReminderEvent.create({ user: userId, reminderId: reminder._id, eventType: 'generated' }); }
    catch (error) { if (error.code !== 11000) throw error; }
  }
}
