import { Reminder } from '../models/Reminder.js';
import { Task } from '../models/Task.js';

export async function backfillTaskReminderState() {
  const enabled = await Task.updateMany({ taskReminderState: { $exists: false }, reminderMode: { $in: ['automatic', null] } }, { $set: { taskReminderState: 'enabled' } });
  const muted = await Task.updateMany({ taskReminderState: { $exists: false }, reminderMode: { $in: ['custom', 'off'] } }, { $set: { taskReminderState: 'muted' } });
  return { enabled: enabled.modifiedCount, muted: muted.modifiedCount };
}

// Keep the documents and their delivery history. Only automatic task cues are retired.
export async function suppressLegacyTaskReminders() {
  const result = await Reminder.updateMany({
    entityType: 'task', autoGenerated: true,
    status: { $in: ['scheduled', 'active', 'snoozed', 'waiting'] },
  }, { $set: { status: 'cancelled', claimUntil: null, processingBy: null } });
  return result.modifiedCount;
}
