import { Task } from '../models/Task.js';
import { Reminder } from '../models/Reminder.js';
import { TaskExecutionEvent } from '../models/TaskExecutionEvent.js';
import { AppError } from '../utils/AppError.js';
import { updateTask } from './taskService.js';
import { getSettingsDocument } from './settingsService.js';
import { getAutomationSettings, automationTimezone } from './automationSettings.service.js';
import { event, markReminderBlocked, snoozeReminder } from './reminders/reminderService.js';

async function record(userId, task, type, channel, metadata = {}) {
  await TaskExecutionEvent.create({ user: userId, task: task._id, type, channel, metadata });
}

async function scheduleCheckIn(userId, task, now, rules, reset = false) {
  if (!rules.taskExecution.startFollowUpEnabled || !rules.taskExecution.maxStartCheckIns) return;
  const settings = await getSettingsDocument(userId);
  const at = new Date(now.getTime() + rules.taskExecution.startCheckInDelayMinutes * 60000);
  const key = `task:${task._id}:checkin`;
  if (await Reminder.exists({ user: userId, policyKey: key, customized: true })) return;
  const fields = {
    user: userId, title: task.title, message: `Still working on ${task.title}?`, source: 'automatic', mode: 'automatic', autoGenerated: true,
    entityType: 'task', entityId: task._id, purpose: 'follow_up', priority: task.priority,
    trigger: { type: 'datetime', at, timezone: automationTimezone(settings, rules) }, nextTriggerAt: at, status: 'scheduled',
    followUp: { enabled: true, delayMinutes: rules.taskExecution.startCheckInDelayMinutes, maxCount: rules.taskExecution.maxStartCheckIns },
    deliveryChannels: Object.entries(settings.reminders?.deliveryChannels || { telegram: true }).filter(([, enabled]) => enabled).map(([name]) => name),
    metadata: { automation: 'checkin' },
    ...(reset ? { followUpCount: 0, triggerCount: 0, deliveredAt: null, acknowledgedAt: null } : {}),
  };
  try { await Reminder.findOneAndUpdate({ user: userId, policyKey: key, customized: { $ne: true } }, { $set: fields, $setOnInsert: { policyKey: key } }, { upsert: true, new: true }); }
  catch (error) { if (error.code !== 11000) throw error; }
}

export async function executeTask(userId, taskId, action, { channel = 'web', reminderId, reason, dueDate, until } = {}) {
  let task = await Task.findOne({ _id: taskId, user: userId, archived: false });
  if (!task) throw new AppError('Task not found', 404);
  const terminal = ['completed', 'cancelled'].includes(task.status);
  if (terminal && !['done'].includes(action)) throw new AppError('Task is already closed', 409);
  const now = new Date();
  const rules = await getAutomationSettings();
  if (action === 'start') {
    if (task.executionState !== 'started') {
      task = await updateTask(userId, taskId, { status: 'in_progress' });
      await Task.updateOne({ _id: taskId, user: userId }, { $set: { executionState: 'started', startedAt: task.startedAt || now, lastStartedAt: now, lastProgressAt: now, lastReminderInteractionAt: now }, $inc: { startCount: 1 } });
      task = await Task.findById(taskId);
      await record(userId, task, 'started', channel);
      await scheduleCheckIn(userId, task, now, rules, true);
    }
  } else if (action === 'continue') {
    if (task.executionState !== 'started') throw new AppError('Start the task first', 409);
    task.lastProgressAt = now;
    task.lastReminderInteractionAt = now;
    await task.save();
    await record(userId, task, 'continued', channel);
    const checkIn = await Reminder.findOne({ user: userId, policyKey: `task:${taskId}:checkin` });
    if (checkIn && checkIn.followUpCount < rules.taskExecution.maxStartCheckIns) await scheduleCheckIn(userId, task, now, rules);
  } else if (action === 'done') {
    if (task.status !== 'completed') {
      task = await updateTask(userId, taskId, { status: 'completed' });
      task.lastReminderInteractionAt = now; await task.save();
      await record(userId, task, 'completed', channel);
    }
  } else if (action === 'blocked') {
    if (reminderId) await markReminderBlocked(userId, reminderId, reason || 'other', '', channel);
    task.executionState = 'blocked'; task.blockedCount += 1; task.lastReminderInteractionAt = now;
    await task.save();
    await record(userId, task, 'blocked', channel, { reason: reason || 'other' });
  } else if (action === 'later' || action === 'stop') {
    task.executionState = 'postponed'; task.postponeCount += 1; task.lastReminderInteractionAt = now;
    await task.save();
    if (reminderId) await snoozeReminder(userId, reminderId, until || new Date(now.getTime() + rules.escalation.cooldownMinutes * 60000), channel);
    await record(userId, task, 'postponed', channel, { reason: reason || action });
  } else if (action === 'reschedule') {
    if (!dueDate || Number.isNaN(new Date(dueDate).getTime())) throw new AppError('Choose a date', 400);
    task = await updateTask(userId, taskId, { dueDate: new Date(dueDate) });
    task.executionState = 'planned'; task.lastReminderInteractionAt = now; await task.save();
    await record(userId, task, 'rescheduled', channel, { dueDate });
  } else if (action === 'backlog') {
    task = await updateTask(userId, taskId, { dueDate: null });
    task.executionState = 'idle'; task.lastReminderInteractionAt = now; await task.save();
    await record(userId, task, 'backlog', channel);
  } else if (action === 'resume') {
    task.executionState = 'planned'; task.lastReminderInteractionAt = now; await task.save();
    await record(userId, task, 'resumed', channel);
  } else if (action === 'drop') {
    task = await updateTask(userId, taskId, { status: 'cancelled' });
    task.lastReminderInteractionAt = now; await task.save();
    await record(userId, task, 'dropped', channel);
  } else throw new AppError('Unknown task action', 400);
  if (reminderId && !['blocked', 'later', 'stop'].includes(action)) {
    const reminder = await Reminder.findOne({ _id: reminderId, user: userId, entityType: 'task', entityId: taskId });
    if (reminder) {
      if (['start', 'backlog', 'drop', 'reschedule'].includes(action) && reminder.status !== 'completed') { reminder.status = 'completed'; reminder.completedAt = now; reminder.acknowledgedAt = now; await reminder.save(); }
      if (action === 'start') await event(reminder, 'acknowledged', channel, { action });
      await event(reminder, 'interacted', channel, { action });
    }
  }
  return Task.findOne({ _id: taskId, user: userId });
}
