import { useEffect, useState } from 'react';
import { NavLink, useLocation, useOutlet } from 'react-router-dom';
import { Bell, BookOpenText, CalendarCheck2, CircleDollarSign, Command, ContactRound, CreditCard, FolderKanban, Gauge, Goal, Landmark, LayoutList, LogOut, Menu, Moon, Plus, ReceiptText, Search, Settings, Sparkles, Sun, WalletCards, X } from 'lucide-react';
import { useApp } from '../context/useApp.js';
import { useAuth } from '../context/useAuth.js';
import { cn } from '../utils/format.js';
import { QuickAdd } from './QuickAdd.jsx';
import { SearchPalette } from './SearchPalette.jsx';
import { AnimatePresence } from 'motion/react';
import { AnimatedPage } from '../animations/AnimatedPage.jsx';
import { api } from '../api/client.js';

const sections = [
  { label: null, items: [['Dashboard', '/', Gauge], ['Tasks', '/tasks', CalendarCheck2], ['Reminders', '/reminders', Bell]] },
  { label: 'Money', items: [['Accounts', '/money/accounts', WalletCards], ['Transactions', '/money/transactions', LayoutList], ['Expenses', '/money/expenses', ReceiptText], ['Income', '/money/income', CircleDollarSign], ['Debts', '/money/debts', Landmark], ['Bills', '/planning/bills', CreditCard], ['Subscriptions', '/planning/subscriptions', Bell]] },
  { label: 'Planning', items: [['Goals & savings', '/planning/goals', Goal], ['Projects', '/personal/projects', FolderKanban], ['Habits', '/personal/habits', Sparkles], ['Wishlist', '/personal/wishlist', BookOpenText]] },
  { label: 'Personal', items: [['Contacts', '/personal/contacts', ContactRound], ['Notes', '/personal/notes', BookOpenText], ['Settings', '/settings', Settings]] },
];

function Logo() { return <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-accent text-sidebar"><div className="h-4 w-4 rounded-full border-[4px] border-sidebar" /></div><div><div className="font-display text-lg font-bold leading-none">Orbit</div><div className="mt-1 text-[9px] font-bold uppercase tracking-[.2em] text-sidebar-muted">Personal OS</div></div></div>; }

function Sidebar({ open, close }) {
  const { user, logout } = useAuth();
  return <aside className={cn('fixed inset-y-0 left-0 z-50 flex w-[264px] flex-col border-r border-sidebar-hover bg-sidebar text-sidebar-text transition-transform duration-200 lg:translate-x-0', open ? 'translate-x-0' : '-translate-x-full')}><div className="flex h-20 items-center justify-between px-5"><Logo /><button className="icon-btn text-sidebar-text lg:hidden" onClick={close}><X /></button></div><nav className="flex-1 overflow-y-auto px-3 pb-5">{sections.map((section, index) => <div key={index} className="mb-5">{section.label && <p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.15em] text-sidebar-muted">{section.label}</p>}{section.items.map(([label, path, Icon]) => <NavLink end={path === '/'} onClick={close} key={path} to={path} className={({ isActive }) => cn('mb-0.5 flex h-10 items-center gap-3 rounded-xl px-3 text-[13px] font-semibold text-sidebar-muted hover:bg-sidebar-hover hover:text-sidebar-text', isActive && 'bg-sidebar-selected text-sidebar-text')}><Icon size={17} /><span>{label}</span></NavLink>)}</div>)}</nav><div className="m-3 rounded-2xl bg-sidebar-hover p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-accent text-xs font-bold text-sidebar">{user?.fullName?.slice(0, 2).toUpperCase() || 'ME'}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{user?.fullName}</p><p className="truncate text-[10px] text-sidebar-muted">{user?.email}</p></div><button title="Log out" onClick={logout} className="text-sidebar-muted hover:text-sidebar-text"><LogOut size={16}/></button></div></div></aside>;
}

export function Layout() {
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false); const { setQuickAddOpen, darkMode, setSettings } = useApp(); const location = useLocation(); const outlet = useOutlet();
  useEffect(() => { setMenu(false); }, [location.pathname]);
  useEffect(() => { const handler = (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setSearch(true); } if (!event.ctrlKey && !event.metaKey && event.key.toLowerCase() === 'n' && !['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement.tagName)) { event.preventDefault(); setQuickAddOpen(true); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [setQuickAddOpen]);
  const toggleTheme = async () => {
    const mode = document.documentElement.classList.contains('dark') ? 'light' : 'dark';
    try { const response = await api.patch('/settings', { appearance: { mode } }); setSettings(response.data); }
    catch { /* Settings remains authoritative if this shortcut cannot be saved. */ }
  };
  return <div className="min-h-screen"><Sidebar open={menu} close={() => setMenu(false)} />{menu && <button aria-label="Close menu" className="fixed inset-0 z-40 bg-sidebar/50 lg:hidden" onClick={() => setMenu(false)} />}<div className="lg:pl-[264px]"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-canvas/90 px-4 backdrop-blur-xl   sm:px-6 lg:h-20 lg:px-8"><button className="icon-btn lg:hidden" onClick={() => setMenu(true)}><Menu size={21} /></button><button onClick={() => setSearch(true)} className="hidden h-10 w-72 items-center gap-2 rounded-xl border border-border bg-surface px-3 text-left text-sm text-muted shadow-sm hover:border-primary   md:flex"><Search size={16} />Search anything…<span className="ml-auto flex items-center gap-1 rounded-md border border-border px-1.5 py-0.5 text-[10px] "><Command size={10} />K</span></button><div className="ml-auto flex items-center gap-1.5"><button className="icon-btn" onClick={toggleTheme} aria-label="Toggle theme">{darkMode ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-btn relative" aria-label="Notifications"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-danger" /></button><button className="btn-primary ml-1 hidden sm:inline-flex" onClick={() => setQuickAddOpen(true)}><Plus size={17} />Quick add</button></div></header><main className="mx-auto max-w-[1500px] px-4 pb-28 pt-6 sm:px-6 lg:px-8 lg:pb-10 lg:pt-8"><AnimatePresence mode="wait" initial={false}><AnimatedPage key={location.pathname}>{outlet}</AnimatedPage></AnimatePresence></main></div><nav className="fixed inset-x-0 bottom-0 z-40 grid h-[70px] grid-cols-5 border-t border-border bg-surface/95 px-2 backdrop-blur-lg   lg:hidden">{[['Home', '/', Gauge], ['Tasks', '/tasks', CalendarCheck2], ['', '#add', Plus], ['Money', '/money/transactions', WalletCards], ['More', '/settings', Menu]].map(([label, path, Icon]) => path === '#add' ? <button key={path} onClick={() => setQuickAddOpen(true)} className="mx-auto -mt-4 grid h-14 w-14 place-items-center rounded-2xl bg-primary text-primary-text shadow-lift  "><Icon size={24} /></button> : <NavLink end={path === '/'} key={path} to={path} className={({ isActive }) => cn('flex flex-col items-center justify-center gap-1 text-[10px] font-bold', isActive ? 'text-primary ' : 'text-muted')}><Icon size={20} /><span>{label}</span></NavLink>)}</nav><QuickAdd /><SearchPalette open={search} onClose={() => setSearch(false)} /></div>;
}
