import mongoose from 'mongoose';
import { Reminder } from '../../models/Reminder.js';
import { ReminderEvent } from '../../models/ReminderEvent.js';
import { Task } from '../../models/Task.js';
import { Debt } from '../../models/Debt.js';
import { Bill, Subscription, Goal } from '../../models/Planning.js';
import { AppError } from '../../utils/AppError.js';
import { pagination } from '../../utils/query.js';
import { getSettingsDocument } from '../settingsService.js';
import { updateTask } from '../taskService.js';
import { nextOccurrence } from './reminderTime.js';
import { buildReminderPlan } from './reminderPolicyService.js';
import { getAutomationSettings } from '../automationSettings.service.js';
import { scheduleSmartTaskCue } from '../smartTaskAutomation.service.js';

const models = { task: Task, debt: Debt, bill: Bill, subscription: Subscription, goal: Goal };
const open = ['scheduled', 'active', 'snoozed', 'waiting'];
const completionLatency = (reminder) =>
  reminder.deliveredAt
    ? Math.max(0, Math.round((Date.now() - reminder.deliveredAt.getTime()) / 60000))
    : null;

function followingRecurringCue(reminder) {
  if (reminder.trigger?.type !== 'recurring') return null;
  if (Object.hasOwn(reminder.metadata || {}, 'postponedNextOccurrenceAt'))
    return reminder.metadata.postponedNextOccurrenceAt;
  if (reminder.metadata?.currentOccurrenceAt)
    return reminder.metadata.recurrenceEnded ? null : reminder.nextTriggerAt;
  return nextOccurrence(reminder.nextTriggerAt, reminder.trigger.recurrence, reminder.trigger.timezone);
}

async function cancelMatching(filter) {
  const rows = await Reminder.find({ ...filter, status: { $in: open } });
  for (const row of rows) {
    row.status = 'cancelled';
    row.claimUntil = null;
    row.processingBy = null;
    await row.save();
    await event(row, 'cancelled');
  }
}

export async function event(reminder, eventType, channel = 'system', metadata = {}) {
  return ReminderEvent.create({
    user: reminder.user,
    reminderId: reminder._id,
    eventType,
    channel,
    metadata,
  });
}

export async function linkedEntity(userId, type, id) {
  if (!models[type] || !mongoose.isValidObjectId(id))
    throw new AppError('Invalid linked entity', 400);
  const entity = await models[type].findOne({ _id: id, user: userId });
  if (!entity) throw new AppError('Linked entity not found', 404);
  return entity;
}

export async function setEntityReminderMode(userId, entityType, entityId, mode) {
  const entity = await linkedEntity(userId, entityType, entityId);
  entity.reminderMode = mode;
  await entity.save();
  await regenerateAutomaticReminderPlan(userId, entityType, entityId);
  return { mode: entity.reminderMode, title: entity.title || entity.name || entity.personName };
}

export function isEntityResolved(type, entity) {
  return (
    !entity ||
    entity.archived ||
    (type === 'task' && ['completed', 'cancelled'].includes(entity.status)) ||
    (type === 'debt' && (entity.status === 'paid' || entity.remainingAmount <= 0)) ||
    (type === 'bill' && entity.status === 'paid') ||
    ((type === 'subscription' || type === 'goal') && entity.status !== 'active')
  );
}

export async function createReminder(userId, input, channel = 'web') {
  const entityType = input.entityType || 'custom';
  if (entityType !== 'custom') {
    const entity = await linkedEntity(userId, entityType, input.entityId);
    if (isEntityResolved(entityType, entity))
      throw new AppError('Linked entity is already resolved', 409);
  }
  if (entityType === 'custom' && input.entityId)
    throw new AppError('A custom reminder cannot have an entity ID', 400);
  const settings = await getSettingsDocument(userId);
  const initialDate = input.trigger?.at || input.nextTriggerAt;
  const date =
    input.trigger?.type === 'recurring' &&
    input.trigger.recurrence?.startDate &&
    new Date(input.trigger.recurrence.startDate) > new Date(initialDate)
      ? input.trigger.recurrence.startDate
      : initialDate;
  if (!date || Number.isNaN(new Date(date).getTime()))
    throw new AppError('A valid reminder time is required', 400);
  if (
    input.nextTriggerAt &&
    input.trigger?.at &&
    new Date(input.nextTriggerAt).getTime() !== new Date(input.trigger.at).getTime()
  )
    throw new AppError('Reminder trigger times do not match', 400);
  if (input.trigger?.type === 'recurring' && !input.trigger.recurrence?.frequency)
    throw new AppError('A recurrence rule is required', 400);
  if (input.trigger?.type === 'recurring' && input.followUp?.enabled)
    throw new AppError('Recurring reminders already repeat', 400);
  const reminder = await Reminder.create({
    ...input,
    user: userId,
    entityType,
    source: 'custom',
    mode: 'custom',
    autoGenerated: false,
    nextTriggerAt: date,
    deliveryChannels:
      input.deliveryChannels ||
      Object.entries(settings.reminders?.deliveryChannels || { telegram: true })
        .filter(([, enabled]) => enabled)
        .map(([name]) => name),
    trigger: { ...input.trigger, timezone: input.trigger?.timezone || settings.timezone, at: date },
  });
  await event(reminder, 'scheduled', channel);
  return reminder;
}

export async function getReminder(userId, id) {
  if (!mongoose.isValidObjectId(id)) throw new AppError('Invalid reminder ID', 400);
  const reminder = await Reminder.findOne({ _id: id, user: userId });
  if (!reminder) throw new AppError('Reminder not found', 404);
  return reminder;
}

export async function listReminders(userId, query = {}) {
  const { page, limit, skip } = pagination(query);
  const filter = { user: userId, archived: false };
  if (query.status) filter.status = query.status;
  if (query.entityType) filter.entityType = query.entityType;
  if (query.entityId) filter.entityId = query.entityId;
  const [data, total] = await Promise.all([
    Reminder.find(filter).sort({ nextTriggerAt: 1 }).skip(skip).limit(limit),
    Reminder.countDocuments(filter),
  ]);
  return { data, pagination: { page, limit, total, pages: Math.ceil(total / limit) } };
}

export async function updateReminder(userId, id, input) {
  const reminder = await getReminder(userId, id);
  const entityType = input.entityType || reminder.entityType;
  const entityId = input.entityId === undefined ? reminder.entityId : input.entityId;
  if (
    reminder.autoGenerated &&
    (entityType !== reminder.entityType || String(entityId) !== String(reminder.entityId))
  )
    throw new AppError('Create a custom reminder to link a different item', 400);
  if (entityType === 'custom' && entityId)
    throw new AppError('A custom reminder cannot have an entity ID', 400);
  if (entityType !== 'custom') {
    const entity = await linkedEntity(userId, entityType, entityId);
    if (isEntityResolved(entityType, entity))
      throw new AppError('Linked entity is already resolved', 409);
  }
  if (
    (input.trigger?.type || reminder.trigger?.type) === 'recurring' &&
    (input.followUp?.enabled ?? reminder.followUp?.enabled)
  )
    throw new AppError('Recurring reminders already repeat', 400);
  if (
    (input.trigger?.type || reminder.trigger?.type) === 'recurring' &&
    !(input.trigger ? input.trigger.recurrence?.frequency : reminder.trigger?.recurrence?.frequency)
  )
    throw new AppError('A recurrence rule is required', 400);
  Object.assign(reminder, input);
  if (input.followUp) reminder.metadata = { ...reminder.metadata, followUpEnded: false };
  if (input.trigger?.at || input.nextTriggerAt) {
    reminder.nextTriggerAt = input.nextTriggerAt || input.trigger.at;
    if (open.includes(reminder.status)) reminder.status = 'scheduled';
    reminder.snoozedUntil = null;
  }
  reminder.claimUntil = null;
  reminder.processingBy = null;
  if (reminder.autoGenerated) reminder.customized = true;
  await reminder.save();
  await event(reminder, 'rescheduled', 'web');
  return reminder;
}

export async function cancelReminder(userId, id, channel = 'web') {
  const reminder = await getReminder(userId, id);
  if (open.includes(reminder.status)) {
    reminder.status = 'cancelled';
    reminder.claimUntil = null;
    reminder.processingBy = null;
    if (reminder.autoGenerated) reminder.customized = true;
    await reminder.save();
    await event(reminder, 'cancelled', channel);
  }
  return reminder;
}

export async function completeReminder(userId, id, channel = 'web') {
  const reminder = await getReminder(userId, id);
  if (!open.includes(reminder.status)) return reminder;
  if (reminder.entityType === 'task') {
    await updateTask(userId, reminder.entityId, { status: 'completed' });
    return getReminder(userId, id);
  } else if (['debt', 'bill'].includes(reminder.entityType)) {
    throw new AppError('Record payment through the linked financial item', 409);
  } else if (reminder.entityType === 'subscription') {
    throw new AppError('Manage the linked subscription in Planning', 409);
  } else if (reminder.trigger?.type === 'recurring') {
    let next = followingRecurringCue(reminder);
    for (let step = 0; step < 1000 && next && new Date(next) <= new Date(); step += 1)
      next = nextOccurrence(next, reminder.trigger.recurrence, reminder.trigger.timezone);
    if (next && new Date(next) <= new Date()) next = null;
    reminder.status = next ? 'scheduled' : 'completed';
    reminder.nextTriggerAt = next || reminder.nextTriggerAt;
    reminder.triggerCount = 0;
    reminder.snoozedUntil = null;
    reminder.acknowledgedAt = new Date();
    const metadata = { ...reminder.metadata };
    delete metadata.postponedNextOccurrenceAt;
    reminder.metadata = { ...metadata, currentOccurrenceAt: null, recurrenceEnded: !next };
    await reminder.save();
  } else {
    reminder.status = 'completed';
    reminder.completedAt = new Date();
    await reminder.save();
  }
  await event(reminder, 'completed', channel, {
    completionLatencyMinutes: completionLatency(reminder),
  });
  return reminder;
}

export async function snoozeReminder(userId, id, until, channel = 'web') {
  const reminder = await getReminder(userId, id);
  const date = new Date(until);
  if (!open.includes(reminder.status) || !Number.isFinite(date.getTime()) || date <= new Date())
    throw new AppError('Choose a future snooze time', 400);
  if (reminder.trigger?.type === 'recurring')
    reminder.metadata = { ...reminder.metadata, postponedNextOccurrenceAt: followingRecurringCue(reminder) };
  reminder.status = 'snoozed';
  reminder.nextTriggerAt = date;
  reminder.snoozedUntil = date;
  reminder.snoozeCount += 1;
  reminder.claimUntil = null;
  reminder.processingBy = null;
  await reminder.save();
  await event(reminder, 'snoozed', channel, {
    until: date,
    durationMinutes: Math.round((date.getTime() - Date.now()) / 60000),
  });
  return reminder;
}

export async function markReminderBlocked(userId, id, reason, note = '', channel = 'web') {
  const reminder = await getReminder(userId, id);
  if (!open.includes(reminder.status)) throw new AppError('Reminder is resolved', 409);
  reminder.status = 'waiting';
  reminder.blockedReason = reason;
  reminder.blockedNote = note;
  reminder.claimUntil = null;
  reminder.processingBy = null;
  await reminder.save();
  await event(reminder, 'blocked', channel, { reason });
  return reminder;
}

export async function resumeReminder(userId, id, at = new Date(), channel = 'web') {
  const reminder = await getReminder(userId, id);
  if (reminder.status !== 'waiting') throw new AppError('Reminder is not waiting', 409);
  if (reminder.trigger?.type === 'recurring')
    reminder.metadata = { ...reminder.metadata, postponedNextOccurrenceAt: followingRecurringCue(reminder) };
  reminder.status = 'scheduled';
  reminder.nextTriggerAt = at;
  reminder.blockedReason = '';
  reminder.blockedNote = '';
  reminder.claimUntil = null;
  reminder.processingBy = null;
  await reminder.save();
  await event(reminder, 'rescheduled', channel, { at });
  return reminder;
}

export async function resolveEntityReminders(userId, entityType, entityId) {
  const rows = await Reminder.find({ user: userId, entityType, entityId, status: { $in: open } });
  for (const row of rows) {
    row.status = 'completed';
    row.completedAt = new Date();
    row.claimUntil = null;
    row.processingBy = null;
    await row.save();
    await event(row, 'completed', 'system', { completionLatencyMinutes: completionLatency(row) });
  }
}

export async function cancelEntityReminders(userId, entityType, entityId) {
  await cancelMatching({ user: userId, entityType, entityId });
}

export async function regenerateAutomaticReminderPlan(
  userId,
  entityType,
  entityId,
  { restore = false } = {},
) {
  const entity = await linkedEntity(userId, entityType, entityId);
  const settings = await getSettingsDocument(userId);
  const automation = await getAutomationSettings();
  if (isEntityResolved(entityType, entity)) {
    if (['cancelled', 'paused'].includes(entity.status) || entity.archived)
      await cancelEntityReminders(userId, entityType, entityId);
    else await resolveEntityReminders(userId, entityType, entityId);
    return [];
  }
  const mode =
    entity.reminderMode || settings.reminders?.defaultEntityModes?.[entityType] || 'automatic';
  if (!settings.reminders?.enabled || !settings.reminders?.automaticEnabled) return [];
  if (mode === 'off' || mode === 'custom') {
    await cancelMatching({ user: userId, entityType, entityId, autoGenerated: true });
    return [];
  }
  if (entityType === 'task' && automation.general.enabled) {
    await cancelMatching({ user: userId, entityType, entityId, autoGenerated: true, customized: false,
      policyKey: { $in: [`task:${entityId}:prepare`, `task:${entityId}:act`, `task:${entityId}:follow-up`] } });
    const cue = await scheduleSmartTaskCue(userId, entity, { rules: automation });
    return cue ? [cue] : [];
  }
  const plan = buildReminderPlan(entityType, entity, settings);
  const keys = plan.map((item) => `${entityType}:${entityId}:${item.key}`);
  await cancelMatching({
    user: userId,
    entityType,
    entityId,
    autoGenerated: true,
    customized: false,
    policyKey: { $nin: keys },
  });
  const results = [];
  for (const item of plan) {
    const policyKey = `${entityType}:${entityId}:${item.key}`;
    let reminder = await Reminder.findOne({ user: userId, policyKey });
    if (reminder?.customized && !restore) {
      results.push(reminder);
      continue;
    }
    if (entityType === 'goal' && reminder?.status === 'scheduled' && !restore) {
      results.push(reminder);
      continue;
    }
    if (reminder && ['active', 'completed'].includes(reminder.status) && !restore) {
      results.push(reminder);
      continue;
    }
    const explanation = [
      `Automatic ${entityType} ${item.purpose.replace('_', ' ')} cue.`,
      entityType === 'goal'
        ? 'Active goal: review progress instead of treating the goal as a task.'
        : `Item status: ${entity.status}.`,
      `Priority: ${item.priority}.`,
      'Delivery is checked against current status, quiet hours, and recent cues.',
    ].join('\n');
    const data = {
      user: userId,
      title: entity.title || entity.name || entity.personName,
      message: item.message,
      source: 'automatic',
      mode: 'automatic',
      autoGenerated: true,
      entityType,
      entityId,
      purpose: item.purpose,
      priority: item.priority,
      trigger: {
        type: entityType === 'goal' ? 'recurring' : 'datetime',
        at: item.when,
        timezone: settings.timezone,
        ...(entityType === 'goal' ? { recurrence: { frequency: 'weekly', interval: 1 } } : {}),
      },
      nextTriggerAt: item.when,
      policyKey,
      status: 'scheduled',
      customized: false,
      deliveryChannels: Object.entries(settings.reminders?.deliveryChannels || { telegram: true })
        .filter(([, enabled]) => enabled)
        .map(([name]) => name),
      metadata: { explanation },
    };
    if (reminder) {
      Object.assign(reminder, data);
      await reminder.save();
    } else {
      try {
        reminder = await Reminder.create(data);
        await event(reminder, 'generated');
      } catch (error) {
        if (error.code !== 11000) throw error;
        reminder = await Reminder.findOne({ user: userId, policyKey });
      }
    }
    results.push(reminder);
  }
  return results;
}
