import { Reminder } from '../../models/Reminder.js';
import { User } from '../../models/User.js';
import { getSettingsDocument } from '../settingsService.js';
import { checkAccess } from '../accessService.js';
import { isEntityResolved, linkedEntity } from './reminderService.js';
import { afterQuietHours, inQuietHours, nextActiveTime } from './reminderTime.js';

export async function coordinateReminder(reminder, now = new Date()) {
  const user = await User.findById(reminder.user);
  if (!user) return { action: 'suppress', reason: 'Owner no longer exists' };
  if (!(await checkAccess(user)).eligible)
    return { action: 'defer', at: new Date(now.getTime() + 86400000), reason: 'Access inactive' };
  const settings = await getSettingsDocument(reminder.user);
  if (!settings.reminders?.enabled)
    return { action: 'defer', at: new Date(now.getTime() + 3600000), reason: 'Reminders disabled' };
  if (
    settings.reminders?.deliveryChannels?.telegram === false &&
    settings.reminders?.deliveryChannels?.web === false
  )
    return {
      action: 'defer',
      at: new Date(now.getTime() + 3600000),
      reason: 'Delivery channels disabled',
    };
  if (reminder.autoGenerated && settings.reminders?.automaticEnabled === false)
    return {
      action: 'defer',
      at: new Date(now.getTime() + 86400000),
      reason: 'Automatic reminders disabled',
    };
  if (reminder.entityType !== 'custom') {
    const entity = await linkedEntity(reminder.user, reminder.entityType, reminder.entityId).catch(
      () => null,
    );
    if (isEntityResolved(reminder.entityType, entity))
      return { action: 'resolve', reason: 'Linked entity resolved' };
  }
  if (reminder.status === 'waiting') return { action: 'defer', reason: 'Waiting for blocker' };
  if (
    reminder.autoGenerated &&
    reminder.purpose === 'follow_up' &&
    (!settings.reminders?.incompleteFollowUpsEnabled ||
      reminder.followUpCount >= (settings.reminders?.maxAutomaticFollowUps ?? 2))
  )
    return { action: 'suppress', reason: 'Follow-up limit' };
  if (inQuietHours(now, settings) && reminder.priority !== 'urgent')
    return { action: 'defer', at: afterQuietHours(now, settings), reason: 'Quiet hours' };
  const activeAt = nextActiveTime(now, settings);
  if (activeAt > now && reminder.priority !== 'urgent')
    return { action: 'defer', at: activeAt, reason: 'Outside active hours' };
  const spacing = (settings.reminders?.minimumReminderSpacingMinutes ?? 120) * 60000;
  if (reminder.entityId && reminder.priority !== 'urgent') {
    const recent = await Reminder.findOne({
      user: reminder.user,
      entityType: reminder.entityType,
      entityId: reminder.entityId,
      _id: { $ne: reminder._id },
      deliveredAt: { $gte: new Date(now.getTime() - spacing) },
    }).sort({ deliveredAt: -1 });
    if (recent)
      return {
        action: 'defer',
        at: new Date(recent.deliveredAt.getTime() + spacing),
        reason: 'Equivalent cue sent recently',
      };
  }
  return { action: 'send' };
}
