import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc.js';
import timezone from 'dayjs/plugin/timezone.js';
import { Task } from '../models/Task.js';
import { Reminder } from '../models/Reminder.js';
import { DailyFocus } from '../models/DailyFocus.js';
import { getSettingsDocument } from '../services/settingsService.js';
import { getAutomationSettings, automationTimezone } from '../services/automationSettings.service.js';
import { scheduleSmartTaskCue } from '../services/smartTaskAutomation.service.js';
import { getDailyFocus, focusDate, focusProgress } from '../services/dailyFocus.service.js';
import { event } from '../services/reminders/reminderService.js';
import { scheduleFocusTaskCues } from '../services/dailyFocusAutomation.service.js';

dayjs.extend(utc); dayjs.extend(timezone);

async function createFocusReminder(userId, focus, kind, sequence, at, settings, message) {
  const policyKey = `focus:${focus.date}:${kind}:${sequence}`;
  const data = { user: userId, title: kind === 'evening' ? 'Daily Focus review' : 'Plan today’s focus', message,
    source: 'automatic', mode: 'automatic', autoGenerated: true, entityType: 'custom', purpose: 'review', priority: 'medium',
    trigger: { type: 'datetime', at, timezone: focus.timezone }, nextTriggerAt: at, status: 'scheduled', policyKey,
    deliveryChannels: Object.entries(settings.reminders?.deliveryChannels || { telegram: true }).filter(([, enabled]) => enabled).map(([name]) => name),
    metadata: { automation: `focus-${kind}`, focusId: focus._id, date: focus.date,
      items: kind === 'evening' ? focus.items.filter((item) => item.task && item.task.status !== 'completed').map((item) => ({ id: String(item.task._id), title: item.task.title })) : [] } };
  try { const reminder = await Reminder.create(data); await event(reminder, 'generated'); return reminder; }
  catch (error) { if (error.code !== 11000) throw error; return Reminder.findOne({ user: userId, policyKey }); }
}

export async function runAutomationForUser(userId, now = new Date(), rules) {
  rules ||= await getAutomationSettings();
  if (!rules.general.enabled || !rules.general.workerEnabled) return;
  const settings = await getSettingsDocument(userId);
  const zone = automationTimezone(settings, rules);
  if (!settings.reminders?.enabled || !settings.reminders?.automaticEnabled) return;
  for await (const task of Task.find({ user: userId, archived: false, reminderMode: 'automatic', dueDate: { $ne: null }, status: { $nin: ['completed', 'cancelled'] } }).cursor()) {
    await scheduleSmartTaskCue(userId, task, { now, rules });
  }
  if (!rules.dailyFocus.enabled) return;
  const date = focusDate(now, zone);
  const clock = dayjs(now).tz(zone).format('HH:mm');
  if (clock < rules.dailyFocus.morningTime && clock < rules.dailyFocus.eveningTime) return;
  let focus = await getDailyFocus(userId, date);
  if (!focus.planningCompleted && rules.dailyFocus.morningEnabled && clock >= rules.dailyFocus.morningTime && clock < rules.dailyFocus.eveningTime) {
    if (!focus.planningStartedAt) {
      await DailyFocus.updateOne({ _id: focus._id, user: userId, planningStartedAt: null }, { $set: { planningStartedAt: now } });
      focus = await getDailyFocus(userId, date);
    }
    const elapsed = now.getTime() - new Date(focus.planningStartedAt).getTime();
    const interval = rules.dailyFocus.planningReminderIntervalMinutes * 60000;
    const max = rules.dailyFocus.planningReminderEnabled ? rules.dailyFocus.maxPlanningReminders : 0;
    const sequence = elapsed < interval ? 0 : Math.min(max, Math.floor(elapsed / interval));
    if (sequence === 0 || (sequence <= max && elapsed >= sequence * interval)) {
      const count = focus.items.length;
      await createFocusReminder(userId, focus, 'morning', sequence, now, settings,
        count ? `${count}/${rules.dailyFocus.maxTasks} selected. What's next? Type done if that's enough.` : 'What are your priorities today? Reply with a task, or /focus.');
    }
  }
  if (rules.dailyFocus.eveningEnabled && clock >= rules.dailyFocus.eveningTime && focus.items.length) {
    const progress = focusProgress(focus);
    const lines = focus.items.map((item) => `${item.task?.status === 'completed' ? '✓' : '□'} ${item.task?.title || 'Removed task'}`);
    await createFocusReminder(userId, focus, 'evening', 0, now, settings, `Today: ${progress.completed}/${progress.total}\n${lines.join('\n')}\nChoose what to do with unfinished tasks.`);
  }
  await scheduleFocusTaskCues(userId, focus, settings, rules, now);
}
